// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqgonbozaushwjufjxgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZ29uYm96YXVzaHdqdWZqeGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzQzODUsImV4cCI6MjA2ODcxMDM4NX0.srPyLGxUONkH2LCXi3XOq19bLppB6qGwtehXHnt5xXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});